### ISSUE TITLE
Naming

### ISSUE THREAD

**Issue by adler-j** [odlgroup/dipp#1]
Shouldn't we go for something more specific? Perhaps mention inverse problems or mention that we're going for utilities.

**Comment by kohr-h** [comment]
Sure, I just picked something completely random. The short version `dllib` is quite ok I think.

**Comment by kohr-h** [comment]
How about "Deep Inverse Problems Utilities" (`dipu`) 😉

**Comment by adler-j** [comment]
Why not just `dip`?

**Comment by kohr-h** [comment]
That's unfortunately [taken on PyPI](https://pypi.org/project/dip/). We can also ignore that package, conflict is quite unlikely.

**Comment by adler-j** [comment]
`dipp` then! Just add package

**Comment by kohr-h** [comment]
Like it, I'll change the name to that!
