### ISSUE TITLE
Git-less installation

### ISSUE THREAD

**Issue by adler-j** [odlgroup/dipp#3]
Users can install the package directly by running

```bash
$ pip install https://github.com/odlgroup/dipp/archive/master.zip
```

we should perhaps change the installation instructions to this.

**Comment by kohr-h** [comment]
Okay, that's a notch easier than to clone the repo. I'd say we add this as the first option and then have another instruction for "installation from source".

**Comment by adler-j** [comment]
Well for people on windows it's lightyears easier since they don't need git (and even on linux, git is typically not installed by default). Not to mention that it avoids clutter.

Your solution sounds great!
